import type { TicketRecord } from "@/lib/types"

export const initialTickets: TicketRecord[] = [
  {
    id: "ticket_conn_1024",
    subject: "Frankfurt config disconnects after a few minutes",
    category: "connection_issue",
    priority: "high",
    status: "waiting_for_support",
    createdAt: "2026-04-10T08:10:00.000Z",
    updatedAt: "2026-04-11T07:42:00.000Z",
    requesterName: "Sina Oshaghi",
    lastReplyPreview: "The connection drops after two to three minutes on iPhone and macOS.",
    lastReplyAuthorType: "user",
    unread: false,
    messages: [
      {
        id: "ticket_conn_1024_msg_1",
        authorType: "user",
        authorName: "Sina Oshaghi",
        body: "Hi, my Frankfurt VMess config connects successfully but disconnects after a few minutes on both iPhone and macOS. It started this morning.",
        createdAt: "2026-04-10T08:10:00.000Z",
      },
      {
        id: "ticket_conn_1024_msg_2",
        authorType: "user",
        authorName: "Sina Oshaghi",
        body: "I also tested mobile data and Wi‑Fi. Same result in both cases.",
        createdAt: "2026-04-11T07:42:00.000Z",
      },
    ],
  },
  {
    id: "ticket_bill_1038",
    subject: "Refund request for duplicate monthly charge",
    category: "refund",
    priority: "normal",
    status: "waiting_for_user",
    createdAt: "2026-04-06T09:20:00.000Z",
    updatedAt: "2026-04-11T09:35:00.000Z",
    requesterName: "Sina Oshaghi",
    lastReplyPreview: "Support replied: please confirm the last four digits of the card used for the duplicate payment.",
    lastReplyAuthorType: "support",
    unread: true,
    messages: [
      {
        id: "ticket_bill_1038_msg_1",
        authorType: "user",
        authorName: "Sina Oshaghi",
        body: "I was charged twice for the Pro monthly renewal on April 1. Can you help review and refund the duplicate payment?",
        createdAt: "2026-04-06T09:20:00.000Z",
      },
      {
        id: "ticket_bill_1038_msg_2",
        authorType: "support",
        authorName: "Tunnel Support",
        body: "We can help with that. Please confirm the last four digits of the card used for the duplicate payment so we can match the charge.",
        createdAt: "2026-04-11T09:35:00.000Z",
      },
    ],
  },
  {
    id: "ticket_cfg_0971",
    subject: "Need help importing VLESS config into v2rayN",
    category: "config_help",
    priority: "normal",
    status: "resolved",
    createdAt: "2026-04-02T14:05:00.000Z",
    updatedAt: "2026-04-04T10:48:00.000Z",
    requesterName: "Sina Oshaghi",
    lastReplyPreview: "Support replied: the config was imported successfully after switching transport mode to gRPC.",
    lastReplyAuthorType: "support",
    unread: false,
    messages: [
      {
        id: "ticket_cfg_0971_msg_1",
        authorType: "user",
        authorName: "Sina Oshaghi",
        body: "My backup Amsterdam config does not import into v2rayN. It says the link is valid but the profile cannot connect.",
        createdAt: "2026-04-02T14:05:00.000Z",
      },
      {
        id: "ticket_cfg_0971_msg_2",
        authorType: "support",
        authorName: "Tunnel Support",
        body: "Please make sure transport mode is set to gRPC and TLS is enabled. We also recommend re-copying the config from the dashboard to avoid hidden characters.",
        createdAt: "2026-04-03T08:22:00.000Z",
      },
      {
        id: "ticket_cfg_0971_msg_3",
        authorType: "user",
        authorName: "Sina Oshaghi",
        body: "That fixed it. The config is connecting now.",
        createdAt: "2026-04-04T10:48:00.000Z",
      },
    ],
  },
  {
    id: "ticket_acc_0884",
    subject: "Could not access dashboard after password reset",
    category: "account_access",
    priority: "low",
    status: "closed",
    createdAt: "2026-03-21T11:00:00.000Z",
    updatedAt: "2026-03-22T07:40:00.000Z",
    requesterName: "Sina Oshaghi",
    lastReplyPreview: "Support closed the ticket after confirming the account access issue was resolved.",
    lastReplyAuthorType: "support",
    unread: false,
    messages: [
      {
        id: "ticket_acc_0884_msg_1",
        authorType: "user",
        authorName: "Sina Oshaghi",
        body: "After resetting my password I could log in once, but the next time the dashboard sent me back to the login page.",
        createdAt: "2026-03-21T11:00:00.000Z",
      },
      {
        id: "ticket_acc_0884_msg_2",
        authorType: "support",
        authorName: "Tunnel Support",
        body: "We refreshed your account session. Please sign in again and let us know if the issue persists.",
        createdAt: "2026-03-21T13:10:00.000Z",
      },
      {
        id: "ticket_acc_0884_msg_3",
        authorType: "user",
        authorName: "Sina Oshaghi",
        body: "Confirmed. I can access the dashboard normally now.",
        createdAt: "2026-03-22T07:10:00.000Z",
      },
      {
        id: "ticket_acc_0884_msg_4",
        authorType: "support",
        authorName: "Tunnel Support",
        body: "Great. We’re closing this ticket for now. If anything changes, open a new one and we’ll help right away.",
        createdAt: "2026-03-22T07:40:00.000Z",
      },
    ],
  },
  {
    id: "ticket_app_1112",
    subject: "Best app setup for Android TV",
    category: "app_setup",
    priority: "low",
    status: "open",
    createdAt: "2026-04-11T05:55:00.000Z",
    updatedAt: "2026-04-11T05:55:00.000Z",
    requesterName: "Sina Oshaghi",
    lastReplyPreview: "I need a simple setup recommendation for Android TV and a config that stays stable for streaming.",
    lastReplyAuthorType: "user",
    unread: false,
    messages: [
      {
        id: "ticket_app_1112_msg_1",
        authorType: "user",
        authorName: "Sina Oshaghi",
        body: "Which client app do you recommend for Android TV? I need something stable for streaming and easy to maintain.",
        createdAt: "2026-04-11T05:55:00.000Z",
      },
    ],
  },
]
