import type { WorkspaceRecord } from "@/features/workspaces/workspace-data"

export const mockWorkspaces: WorkspaceRecord[] = [
  {
    id: "ws-registry-core",
    name: "Registry Core",
    team: "Platform Systems",
    teamEmail: "platform@registry.studio",
    framework: "Next.js",
    style: "New York v4",
    releaseChannel: "Stable",
    status: "Healthy",
    installedComponents: 84,
    monthlyInstalls: 16400,
    lastReleaseLabel: "v4.18.2 shipped 2 days ago",
  },
  {
    id: "ws-marketing-site",
    name: "Marketing Site",
    team: "Growth",
    teamEmail: "growth@registry.studio",
    framework: "Vite",
    style: "New York v4",
    releaseChannel: "Beta",
    status: "Syncing",
    installedComponents: 46,
    monthlyInstalls: 9200,
    lastReleaseLabel: "v4.19.0-beta.3 synced this morning",
  },
  {
    id: "ws-admin-console",
    name: "Admin Console",
    team: "Operations",
    teamEmail: "ops@registry.studio",
    framework: "Monorepo",
    style: "Base Nova",
    releaseChannel: "Stable",
    status: "Needs review",
    installedComponents: 62,
    monthlyInstalls: 8700,
    lastReleaseLabel: "v4.17.5 pending design review",
  },
  {
    id: "ws-clinician-portal",
    name: "Clinician Portal",
    team: "Care Tools",
    teamEmail: "care-tools@registry.studio",
    framework: "Next.js",
    style: "New York v4",
    releaseChannel: "Canary",
    status: "Healthy",
    installedComponents: 58,
    monthlyInstalls: 7100,
    lastReleaseLabel: "canary.84 deployed 6 hours ago",
  },
  {
    id: "ws-patient-app",
    name: "Patient App",
    team: "Experience",
    teamEmail: "experience@registry.studio",
    framework: "Next.js",
    style: "Radix Nova",
    releaseChannel: "Beta",
    status: "Healthy",
    installedComponents: 51,
    monthlyInstalls: 11200,
    lastReleaseLabel: "beta.22 validated yesterday",
  },
  {
    id: "ws-design-docs",
    name: "Design Docs",
    team: "Design Systems",
    teamEmail: "design-systems@registry.studio",
    framework: "Vite",
    style: "New York v4",
    releaseChannel: "Stable",
    status: "Healthy",
    installedComponents: 39,
    monthlyInstalls: 5300,
    lastReleaseLabel: "v4.18.0 published last week",
  },
  {
    id: "ws-tooling-lab",
    name: "Tooling Lab",
    team: "Developer Experience",
    teamEmail: "dx@registry.studio",
    framework: "Monorepo",
    style: "Base Nova",
    releaseChannel: "Canary",
    status: "Syncing",
    installedComponents: 27,
    monthlyInstalls: 3900,
    lastReleaseLabel: "canary.12 waiting for docs sync",
  },
  {
    id: "ws-support-console",
    name: "Support Console",
    team: "Support Ops",
    teamEmail: "support@registry.studio",
    framework: "Next.js",
    style: "New York v4",
    releaseChannel: "Stable",
    status: "Needs review",
    installedComponents: 33,
    monthlyInstalls: 2400,
    lastReleaseLabel: "v4.17.8 blocked by copy review",
  },
]

